In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Opening a csv file from the local Directory

In [27]:
import os

print("Current Notebook Directory:", os.getcwd())
print("Files in current directory:", os.listdir())

Current Notebook Directory: /Users/manjushwarkhairkar/AI-agriculture-yield-production/Notebooks
Files in current directory: ['04_Evaluation_Deployment.ipynb', '03_modelling.ipynb', '02_eda.ipynb', '.ipynb_checkpoints', '01_Data_preprocessing.ipynb']

In [52]:

df = pd.read_csv('../Datasets/rice_data_outlier_removed.csv')

In [53]:
df

,Unnamed: 0,Year,State Name,Dist Name,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha),State_en
0,0,2010,Chhattisgarh,Durg,777.92,1319.18,1695.77,3
1,1,2011,Chhattisgarh,Durg,806.55,1416.48,1756.23,3
2,2,2012,Chhattisgarh,Durg,807.07,1534.22,1900.97,3
3,3,2013,Chhattisgarh,Durg,819.44,1296.24,1581.86,3
4,4,2014,Chhattisgarh,Durg,834.87,1444.24,1729.89,3
...,...,...,...,...,...,...,...,...
2464,2479,2013,Jharkhand,Singhbhum,267.06,579.70,2170.67,7
2465,2480,2014,Jharkhand,Singhbhum,256.33,586.63,2288.57,7
2466,2481,2015,Jharkhand,Singhbhum,263.21,264.71,1005.70,7
2467,2482,2016,Jharkhand,Singhbhum,224.05,319.01,1423.84,7
2468,2483,2017,Jharkhand,Singhbhum,386.91,669.97,1731.62,7

In [54]:
df.sample(4)

,Unnamed: 0,Year,State Name,Dist Name,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha),State_en
1957,1972,2010,Himachal Pradesh,Chamba,2.62,3.16,1206.11,6
2075,2090,2016,Kerala,Malappuram,7.14,17.21,2410.50,9
1619,1634,2016,Uttar Pradesh,Jalaun,0.42,0.65,1552.13,17
2026,2041,2015,Himachal Pradesh,Sirmaur,5.37,6.35,1182.50,6

In [22]:
new_df.to_csv(r'C:\Users\devin\AI-agriculture-yield-prediction\Datasets\rice_data_outlier_removed.csv', index=False)

In [ ]:
# Lets update these graph and add some high level content